# Generated by Django 6.0.3 on 2026-04-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applog_requestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_next_at', models.DateTimeField()),
                ('last_fetch_at', models.DateTimeField()),
            ],
        ),
    ]
