# Generated by Django 6.0.3 on 2026-04-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fetchrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppLog',
        ),
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
