# Generated by Django 6.0.3 on 2026-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_applog_delete_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='competitions_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
