# Generated by Django 6.0.3 on 2026-07-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_player_is_eligible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchRecord',
        ),
    ]
