# Generated by Django 6.0.3 on 2026-07-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_fetchrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
